service: daily-mail

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.10
  stage: prod
#  environment:
#    TG_BOT_TOKEN: ${env.TG_BOT_TOKEN}
#    TG_CHAT_ID: ${env.TG_CHAT_ID}

functions:
  run:
    handler: handler.run