name: Deploy main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Install npm dependencies
        run: npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          envkey_TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          file_name: .env
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}