name: Deploy main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          envkey_TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          file_name: .env.prod
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}